version: "2"
services:
  mongo:
    image: mongo:latest
    container_name: ark-postgres
    ports:
        - "127.0.0.1:27017:27017"
  redis:
    image: redis:latest
    ports:
        - "127.0.0.1:6379:6379"
  web:
    build: .
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"